server:
  port: 8080
  tomcat:
    max-connections: 20
    threads:
      max: 20
      min-spare: 10
    accept-count: 10

#应用配置
app:
  config:
    api-version: v1
    #跨域: 开发阶段设置不限制
    cross-origin: "*"
    #sc渠道
    group-buy-market:
      api-url: http://localhost:8091
      notify-url: http://localhost:8080/api/v1/alipay/group_buy_notify
      source: s01
      channel: c01

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/s-pay-mall?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat
  rabbitmq:
    host: 192.168.6.135
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        prefetch: 1 # 每个消费者的并发线程数
    template:
      delvery-mode: persistent # 消息持久化
    config:
      #消费者
      consumer:
        #交换机
        exchange: group_buy_market_exchange
        #消息主题配置：路由Key、队列
        topic_team_success:
          #消息主题
          routing-key: topic.team_success
          # 消息队列
          queue: s_pay_mall_queue_2_topic_team_success
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location: classpath:/mybatis/config/mybatis-config.xml

# Redis
redis:
  sdk:
    config:
      host: localhost
      port: 6379
      pool-size: 10
      min-idle-size: 5
      idle-timeout: 30000
      connect-timeout: 5000
      retry-attempts: 3
      retry-interval: 1000
      ping-interval: 60000
      keep-alive: true

# 支付宝支付 - 沙箱 https://opendocs.alipay.com/common/02kkv7
alipay:
  enabled: true
  app_id: 9021000159653100
  merchant_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCkRWSLzad8VoSHw4C0AD4IyqyqiuV6APiBR8E3XPlt3xYfqLZvHyxKroa2io1VxtSXutLZYg6+kAbo9CZI/OuHw0ZsHMj3Xl73WWmiZ0cM5kgiirf0mKwk45kB/I6QdRZidulhQCLaHMnPJipch1Ni0Hf6Qu/gl7+fNxebE3od/TC5Sv8jo2LrJJZVce2PCiEvoczwvTHht5WJ7xs+UzAxCZyOnwtb2bagA+hp5Wmhx7uMXz+W+T6t3hp69jRDlYA+0Lw1ChNS2nQNkeoCbhAMF5qSUjiKYsIcqImF7zBfn/uVapRJmvWIL0LHA5N2CrEjYqBr32RYtK+9mEpvlQxtAgMBAAECggEANO+DsiWIhmHe/Vz72YWGeBDPyXlO75zmd8qmse+NFWHhYDxe5bo27K4HDUXiu7SCB48VqSWXOMNy5pjeyYBvaeV8iRRRkp1fnve6ObJsS/TdY/wtwW19c7nAMcqwKk8A8qP9GvCvCnhidBWJax3UujARqZzubgKYpnb7bWa+YHEVmjNIwXzkTnC1RhdqYsykpAOB/XN/See/W6X3jXraxkrNtAhJqZgMil/fLYf4JG1IU8ywJ/kGcvsfOHE4EVb/h55v7yZ+sQz6oqktxEtIhs/45RdTEPDtCr/Rfkcf3nN41bbsFA3EEwt5Ti38/jCI2G7h7e+92fpDM5sYil6vBQKBgQDOFsIf16SsIMv6lGA/JImtiNyu0qCRYrBm8pXZCCK/kEVmXLxu1WHd7NFTk6wbBiZqgidPslbLl7QkQtU4KrHsJe3v7nGvQe2tfYjruc0C1PwJJ0uqGsGjEVaD6ZbOithBVW2jy/ufBYeW/6fbcaGFJM9wogfo+9GG+mBf/sbDpwKBgQDMDfvJjZoz4hrKcAbNYnPaFa66iaNmbY9kLURYm3lTPjWWOcO0XsjwidVC3UoAskfWJfP1aaHyjA2w/CH/LncHjLv3FTGct3tz7ssbPKb1BN50G1ixE6+L4KdFgOTfMygB5koulCu7HIKZLQ527uZ/opkfOFwrZhk4YITseLHBywKBgQDL3M1o7Es0DjlZBf9zVrRumi0bLrWxO3ueSqeaiia9cnyENoYb6S6ndkTXNQQRs3K690bl2ldrjAShvg7nQazBGgAV0LxajpALh1uzOxemjoNGlr2NZmxX36XCVYZdiBFGB7iuR/D/LFwlLX6hX/VUHMaq90111ew9Zl2BeCisjwKBgD/Js0cre+PyL5vO72FvAHZRRuDLPAg+AZA4UmA8oe2yyb+faR1OcBQ5kjAnywVyteAs1xmFnvmabIFCIEKMPOtgRDYWKv8poG76XAW0rSB1GDFFhzE7zSm13bRteZ6IeF43pkLvUMhaPj0yB46IWgfWRXWsAawTa5jjG0ps5GyHAoGAGaZsv5HsstW6RpEWIi/qTeBTQ6cG0FegtrBfrmXbW6VWZEoy2WJrDNNyLaT9uoQsmDE8YJbhoOVsamKet/h2Xv5cwfhQrkuzFc+ffhJrQzfHv6zxRKXlQl6jPoWTEpEqHMP7yCefryZ3VzHGFFWIxfILicTiJxCpLfwdI1Qm7wg=
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAr+0NfxRKO0ilwKYj/eDuoibVq2aZE0DOPkAdsxw50Up6wZ7hT4P7ohhzTtizVdS3LjbSmMT+782pnp0XQJpPHe0I4BSaSdRce+pKSVmzi4DhnUHFOtfVUR7VkL0U4P8lETnyf/9KbEryH5lZOTwF1olvJXj4KpFIb+54KnhcES2O2QWUNp/gCgqQb8+AihIsHz5xItlWjp0pu4VA36LCAIyRPmtZnIQKoKaKaMoyZfhUSI0xJdLf68I5HcKNer/fasbOuK51zZmXHoD7beGJ4lWUk0Ph25ZJkGpkrsRAPGSysLoXtuAMx5e3r/KNf6RuO56ZgqHx9BMhgs7jReJ48QIDAQAB
  notify_url: http://doom15.nat100.top/api/v1/alipay/pay_notify
  return_url: https://gaga.plus
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do

weixin:
  config:
    originalid: gh_ff25205ba449
    token: 3A3a
    app-id: wx2d068dc8d3b3b591
    app-secret: e9c6939d56a65e2b65c9c2407267e70e
    #    template_id: of8No7dMlLQjIhNwi9kyYYw4c0fszoqLVXMiROZGhRw #登录成功
    template_id_2: -yYiA2HCKq5t1f_WIpyqCuNqaRQkl9JfweT4h5fqcsY #显示登录IP地址、地区、登录时间

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml
